# Generated by Django 5.2 on 2025-05-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Tittle',
            new_name='Title',
        ),
    ]
