# Generated by Django 5.2 on 2025-05-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_tittle_menu_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ID_menu',
        ),
    ]
