# Generated by Django 5.2 on 2025-05-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_menu_id_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ID_booking',
        ),
    ]
